### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
vector = np.random.rand(10)

matrix = np.array([
    [11, 20, 29],
    [14, 23, 32],
    [17, 26, 35]
])

print("Вектор:")
print(vector)
print("Розмір вектора:", vector.shape)

print("\nМатриця:")
print(matrix)
print("Розмір матриці:", matrix.shape)


Вектор:
[0.8306342  0.84817061 0.8367944  0.68911457 0.81176612 0.58500792
 0.89245941 0.73805194 0.32938157 0.46933791]
Розмір вектора: (10,)

Матриця:
[[11 20 29]
 [14 23 32]
 [17 26 35]]
Розмір матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [2]:
import numpy as np

vector = np.random.rand(10)

matrix = np.array([
    [11, 20, 29],
    [14, 23, 32],
    [17, 26, 35]
])

vector_plus_10 = np.round(vector + 10, 2)
matrix_times_2 = matrix * 2
vector_squared = np.square(vector)

print("Вектор (оригінальний):")
print(vector)
print("Розмір вектора:", vector.shape)

print("\nВектор + 10 (округлений):")
print(vector_plus_10)

print("\nМатриця (оригінальна):")
print(matrix)
print("Розмір матриці:", matrix.shape)

print("\nМатриця * 2:")
print(matrix_times_2)

print("\nВектор (квадрат кожного елемента):")
print(vector_squared)

Вектор (оригінальний):
[0.24476149 0.4348098  0.43241822 0.62836278 0.09872279 0.45000413
 0.22791716 0.77835699 0.67662022 0.10223582]
Розмір вектора: (10,)

Вектор + 10 (округлений):
[10.24 10.43 10.43 10.63 10.1  10.45 10.23 10.78 10.68 10.1 ]

Матриця (оригінальна):
[[11 20 29]
 [14 23 32]
 [17 26 35]]
Розмір матриці: (3, 3)

Матриця * 2:
[[22 40 58]
 [28 46 64]
 [34 52 70]]

Вектор (квадрат кожного елемента):
[0.05990819 0.18905956 0.18698552 0.39483979 0.00974619 0.20250372
 0.05194623 0.60583961 0.45781493 0.01045216]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [3]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [5]:

result_matrix = np.dot(B, A)
result_with_C = np.dot(result_matrix, C)
result_with_D = np.dot(result_matrix, D)

print("\nМатриця A:")
print(A)

print("\nМатриця B:")
print(B)

print("\nМатриця C:")
print(C)

print("\nМатриця D:")
print(D)

print("\nРезультуюча матриця (B x A):")
print(result_matrix)

print("\nРезультат множення result_matrix на вектор C:")
print(result_with_C)

print("\nРезультат множення result_matrix на матрицю D:")
print(result_with_D)


Матриця A:
[[0.18 0.53]
 [0.75 0.47]
 [0.35 0.21]]

Матриця B:
[[0.17 0.58 0.75]
 [0.38 0.11 0.15]]

Матриця C:
[[0]
 [1]]

Матриця D:
[[0 1]
 [1 0]]

Результуюча матриця (B x A):
[[0.7281 0.5202]
 [0.2034 0.2846]]

Результат множення result_matrix на вектор C:
[[0.5202]
 [0.2846]]

Результат множення result_matrix на матрицю D:
[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [6]:
transposed_result_matrix = result_matrix.T
transposed_vector = vector.T

column_vector = np.expand_dims(vector, axis=1)
transposed_column_vector = column_vector.T

print("\nТранспонована матриця result_matrix:")
print(transposed_result_matrix)

print("\nТранспонований вектор vector:")
print(transposed_vector)
print("Форма транспонованого вектора:", transposed_vector.shape)

print("\nРезультат операції numpy.expand_dims над vector (column_vector):")
print(column_vector)
print("Форма column_vector:", column_vector.shape)

print("\nТранспонований column_vector:")
print(transposed_column_vector)
print("Форма транспонованого column_vector:", transposed_column_vector.shape)


Транспонована матриця result_matrix:
[[0.7281 0.2034]
 [0.5202 0.2846]]

Транспонований вектор vector:
[0.24476149 0.4348098  0.43241822 0.62836278 0.09872279 0.45000413
 0.22791716 0.77835699 0.67662022 0.10223582]
Форма транспонованого вектора: (10,)

Результат операції numpy.expand_dims над vector (column_vector):
[[0.24476149]
 [0.4348098 ]
 [0.43241822]
 [0.62836278]
 [0.09872279]
 [0.45000413]
 [0.22791716]
 [0.77835699]
 [0.67662022]
 [0.10223582]]
Форма column_vector: (10, 1)

Транспонований column_vector:
[[0.24476149 0.4348098  0.43241822 0.62836278 0.09872279 0.45000413
  0.22791716 0.77835699 0.67662022 0.10223582]]
Форма транспонованого column_vector: (1, 10)
